alias:
  default: &default
    working_directory: /tmp/github.com/kpango/rust-musl-builder
    docker:
      - image: circleci/buildpack-deps:latest
        environment:
          ORG_NAME: "kpango"
          REPO_NAME: "rust-musl-builder"
          IMAGE_NAME: "dev"
          GITHUB_API: "https://api.github.com/"
          DOCKER_USER: "kpango"
  setup_remote_docker: &setup_remote_docker
    version: 18.06.0-ce
    docker_layer_caching: true

version: 2
jobs:
  build:
    <<: *default
    steps:
      - setup_remote_docker: *setup_remote_docker
      - checkout
      - run:
          name: check docker version
          command: |
            docker version
      - run:
          name: docker image build
          command: |
            # env DOCKER_BUILDKIT=1 docker build -t ${ORG_NAME}/${IMAGE_NAME}:latest .
            docker build -t ${ORG_NAME}/${IMAGE_NAME}:latest .
      - run:
          name: save image
          command: |
            docker image save ${ORG_NAME}/${IMAGE_NAME}:latest > ./docker-image.tar
      - persist_to_workspace:
          root: .
          paths:
            - .
  publish_nightly:
    <<: *default
    steps:
      - setup_remote_docker: *setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: load image from tar
          command: |
            docker load -i ./docker-image.tar
      - run:
          name: tag to latest
          command: |
            docker tag ${ORG_NAME}/${IMAGE_NAME}:latest ${ORG_NAME}/${IMAGE_NAME}:nightly
      - run:
          name: docker login
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: push image to registory
          command: |
            docker push ${ORG_NAME}/${IMAGE_NAME}
  publish:
    <<: *default
    steps:
      - setup_remote_docker: *setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: load image from tar
          command: |
            docker load -i ./docker-image.tar
      - run:
          name: tag to latest
          command: |
            docker tag ${ORG_NAME}/${IMAGE_NAME}:latest ${ORG_NAME}/${IMAGE_NAME}:$CIRCLE_TAG
      - run:
          name: docker login
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: push image to registory
          command: |
            docker push ${ORG_NAME}/${IMAGE_NAME}
  versioning:
    <<: *default
    steps:
      - checkout
      - run:
          name: check
          command: |
            mkdir -p $HOME/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            LAST_COMMIT=`git log -1 --pretty=%B`
            VERSION=`git describe --abbrev=0 --tags`
            touch ./.tag
            if [ ! -z "`git diff $VERSION`" -o -z "$VERSION" ]; then
              VERSION=${VERSION:-'0.0.0'}
              MAJOR="${VERSION%%.*}"; VERSION="${VERSION#*.}"
              MINOR="${VERSION%%.*}"; VERSION="${VERSION#*.}"
              PATCH="${VERSION%%.*}"; VERSION="${VERSION#*.}"
              if echo $LAST_COMMIT | grep "\[\(major\|MAJOR\)\]" > /dev/null; then
                MAJOR=$((MAJOR+1))
                echo "$MAJOR.0.0" > ./.tag
              elif echo $LAST_COMMIT | grep "\[\(minor\|MINOR\)\]" > /dev/null; then
                MINOR=$((MINOR+1))
                echo "$MAJOR.$MINOR.0" > ./.tag
              elif echo $LAST_COMMIT | grep "\[\(patch\|PATCH\)\]" > /dev/null; then
                PATCH=$((PATCH+1))
                echo "$MAJOR.$MINOR.$PATCH" > ./.tag
              fi
            fi
      - persist_to_workspace:
          root: .
          paths:
            - .
  push:
    <<: *default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: push tag and check PR body
          command: |
            mkdir -p $HOME/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            TAG=`cat ./.tag`
            if [ ! -z "$TAG" ]; then
              echo $TAG
              git tag $TAG
              git push https://${GITHUB_ACCESS_TOKEN}:x-oauth-basic@github.com/${ORG_NAME}/${REPO_NAME} --tags
            fi
      - persist_to_workspace:
          root: .
          paths:
            - .
  gh_release:
    <<: *default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: release
          command: |
            mkdir -p $HOME/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            TAG=`cat ./.tag`
            if [ ! -z "$TAG" ]; then
              echo "Create release: ${TAG}"
              curl -H "Authorization: token ${GITHUB_ACCESS_TOKEN}" \
                   -X POST \
                   -d "{\"tag_name\": \"${TAG}\"}" \
                   ${GITHUB_API}repos/${ORG_NAME}/${REPO_NAME}/releases
            fi

workflows:
  version: 2
  build:
    jobs:
      - build
      - publish_nightly:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - versioning:
          filters:
            branches:
              only:
                - master
      - push:
          requires:
            - versioning
      - gh_release:
          requires:
            - push
  release:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
